export const defaultTheme = {
  colors: {
    red: '#E63946',
    background: '#F1FAEE',
    black: '#1C1B20',
    white: '#fff',
    foreground: '#919186',
    darkBlue: '#1D3557',
    mediumBlue: '#457B9D',
    lightBlue: '#A8DADC',
    darkGrey: '#333',
    grey: '#4C4A57',
    lightGrey: '#808080',
  },
  fonts: {
    heroIntro: 'Courier Prime',
    rabbitScroll: 'Courier Prime',
    landingPageSectionHeading: 'Courier Prime',
    landingPageCardButtons: 'Courier Prime',
    contactTerminal: 'Courier Prime',
    heroGreeting: 'Recursive',
    landingPageComment: 'Lato',
    body: 'Recursive',
  },
};
